# CircuitPython Config
CIRCUITPY_WIFI_SSID = "MY_WIFI_SSID"
CIRCUITPY_WIFI_PASSWORD = "MY_WIFI_PASSWORD"
CIRCUITPY_WEB_API_PASSWORD = "MY_CIRCUITPY_PASSWORD"
CIRCUITPY_WEB_API_PORT = 80

# MQTT Config
MQTT_BROKER = "MY_MQTT_BROKER"
MQTT_PORT = 1883
MQTT_USER = "MY_MQTT_USERNAME"
MQTT_PASSWORD = "MY_MQTT_PASSWORD"
MQTT_TOPIC = "my/mqtt/topic"
